Vagrant.configure("2") do |config|

  config.vm.define "metasploitable" do |c|
    c.vm.box = "rapid7/metasploitable3-ub1404"
    c.vm.box_version = "0.1.12-weekly"
    c.vm.network "private_network", ip: "192.168.60.10"
    c.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nictrace2", "on", "--nictracefile2", "metasploitable-private_network.pcap"]
    end

    # This box does not come with VirtualBox Guest Additions, so its
    # default synced folder will fail. Disable it.
    c.vm.synced_folder ".", "/vagrant", disabled: true

    # By default, this box does not accept ICMP pings. Allow them.
    c.vm.provision "shell", inline: "iptables -I INPUT --proto icmp -j ACCEPT"

    # This box does not ship with the Vagrant default insecure key, so
    # we have to tell Vagrant how to log in (using its password).
    c.ssh.password = "vagrant"
  end

  config.vm.define "scanner" do |c|
    c.vm.box = "debian/buster64"
    c.vm.network "private_network", ip: "192.168.60.11"
    c.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nictrace2", "on", "--nictracefile2", "scanner-private_network.pcap"]
    end
    c.vm.provision "shell", path: "provision/provision.sh"
    c.vm.post_up_message = <<~EOF
                   ______
                ,'"       "-._
              ,'              "-._ _._
              ;              __,-'/   |
             ;|           ,-' _,'"'._,.
             |:            _,'      |\\ `.
             : \\       _,-'         | \\  `.
              \\ \\   ,-'             |  \\   \\
               \\ '.         .-.     |       \\
                \\  \\         "      |        :
                 `. `.              |        |
                   `. "-._          |        ;
                   / |`._ `-._      L       /
                  /  | \\ `._   "-.___    _,'
                 /   |  \\_.-"-.___   """"
                 \\   :            /"""
                  `._\\_       __.'_
             __,--''_ ' "--'''' \\_  `-._
       __,--'     .' /_  |   __. `-._   `-._
      <            `.  `-.-''  __,-'     _,-'
       `.            `.   _,-'"      _,-'
         `.            ''"       _,-'
           `.                _,-'
             `.          _,-'
               `.   __,'"
                 `'"

      ~~~~~~~~~~~ Anarcho-Tech NYC - Network Scanning ~~~~~~~~~~~

      Log in to your scanner machine with:

          vagrant ssh scanner

      Your scanner is equipped with several helpful utilities such as
      `nc`, `traceroute`, `whois`, `nmap`, `tshark`, and more.

      Once logged in, try scanning these demo hosts:

          scanme.nmap.org
          192.168.88.10

      Good luck!

      Please use what you learn here for the betterment of humanity. Only share what
      you know with the people who you believe will do the same. Remember, intention
      is not impact. Kill all Nazis, kill all cops, especially the ones inside ourselves.
    EOF
  end

end
