Vagrant.configure("2") do |config|

  config.vm.define "metasploitable" do |c|
    c.vm.box = "rapid7/metasploitable3-ub1404"
    c.vm.box_version = "0.1.12-weekly"
    c.vm.network "private_network", ip: "192.168.88.10"
  end

  config.vm.define "scanner" do |c|
    c.vm.box = "debian/buster64"
    c.vm.network "private_network", ip: "192.168.88.11"
    c.vm.provision "shell", inline: <<~EOF
      export DEBIAN_FRONTEND=noninteractive
      echo "wireshark wireshark-common/install-setuid boolean true" | debconf-set-selections
      apt update && apt install --yes dnsutils whois nmap tcpdump tshark
      usermod -a -G wireshark vagrant
    EOF

    c.vm.post_up_message = <<~EOF
      Log in to your scanner machine with:

          vagrant ssh scanner

      Your scanner is equipped with several helpful utilities such as
      `nmap`, `whois`, `traceroute`, `nc`, and others.

      Once logged in, try scanning these demo hosts:

          scanme.nmap.org
          192.168.88.10

      Good luck!
    EOF
  end

end
