Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provision "shell", inline: <<~EOF
    # Install dependencies and extra utilities.
    apt update
    apt install --yes xinit openbox xterm keepassxc firefox-esr \
        build-essential libssl-dev libgmp-dev libpcap-dev \
        zlib1g-dev libbz2-dev libkrb5-dev libnss3-dev

    # Build John the Ripper from source because we want the "Jumbo"
    # (community) edition, not merely the core JtR in the Debian repo.
    mkdir -p src
    john_version="1.9.0"
    echo "Downloading John the Ripper ${john_version} Jumbo Edition ..."
    wget --quiet -O src/john-${john_version}-jumbo-1.tar.xz \
        https://www.openwall.com/john/k/john-${john_version}-jumbo-1.tar.xz
    tar -C src -xJvf src/john-${john_version}-jumbo-1.tar.xz
    cd src/john-${john_version}-jumbo-1/src
    ./configure && make && make install
    cd -

    # Add John run directory to path and Bash completion script.
    cat <<PROFILE > ~vagrant/.bash_profile
    export PATH=\\$PATH:\\$HOME/src/john-${john_version}-jumbo-1/run
    source \\$HOME/src/john-${john_version}-jumbo-1/run/john.bash_completion
    PROFILE

    # Symlink lab files.
    for i in $(ls /vagrant/*.txt); do
        ln -s "$i" ~vagrant/src/john-${john_version}-jumbo-1/run/"$(basename $i)"
    done

    # Fixup permissions.
    chown -R vagrant:vagrant ~vagrant
  EOF
  config.vm.post_up_message = <<-EOF

        ___    ____   ______                                  __  _
       /   |  / / /  / ____/___  _________  ____  _________ _/ /_(_)___  ____  _____
      / /| | / / /  / /   / __ \\/ ___/ __ \\/ __ \\/ ___/ __ `/ __/ / __ \\/ __ \\/ ___/
     / ___ |/ / /  / /___/ /_/ / /  / /_/ / /_/ / /  / /_/ / /_/ / /_/ / / / (__  )
    /_/  |_/_/_/   \\____/\\____/_/  / .___/\\____/_/   \\__,_/\\__/_/\\____/_/ /_/____/
                                  /_/
        ___                 ____             __                 __
       /   |  ________     / __ )____ ______/ /_____ __________/ /____
      / /| | / ___/ _ \\   / __  / __ `/ ___/ __/ __ `/ ___/ __  / ___/
     / ___ |/ /  /  __/  / /_/ / /_/ (__  ) /_/ /_/ / /  / /_/ (__  )
    /_/  |_/_/   \\___/  /_____/\\__,_/____/\\__/\\__,_/_/   \\__,_/____/

    ~~~~~~~~~~~~~~~~~~~~~~~ Anarcho-Tech NYC - Hash Cracking ~~~~~~~~~~~~~~~~~~~~~~~

    You now have a virtual machine with John the Ripper installed.
    John the Ripper (also known as JtR) is a free, fast hash cracking
    utility that can be used to "recover" passwords from their hashed
    equivalents.

    To begin, log in to the virtual machine and then run move to the
    directory in which John the Ripper has been installed:

        vagrant ssh
        cd $(dirname $(which john))

    Then, use commands such as `john` and `hashcat` to try and crack
    the hashes in the `evilcorp-intl.com.shadow.txt` shadow file.

    Please use what you learn here for the betterment of humanity. Only share what
    you know with the people who you believe will do the same. Remember, intention
    is not impact. Kill all Nazis, take down all corporations.

        "You don't take down a conglomerate by shooting them in the heart.
         That's the thing about conglomerates: they don't have hearts.
         You take them down limb by limb. And as they unravel, their illusion
         of control unravels."
            --Mr. Robot
  EOF
end
