Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  config.vm.provision "shell", path: "provision/install-openvpn.sh"

  config.vm.define "server" do |c|
    c.vm.network "private_network", ip: "192.168.62.2"
  end

  config.vm.define "client" do |c|
    c.vm.network "private_network", ip: "192.168.62.3"
    c.vm.post_up_message = <<~EOF
                              IIIIIMMMMMMMMMMMMIIIII
                          IIMMMMMMMMMMMMMMMMMMMMMMMMMMIII
                      IIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMII
                   IIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMII
                 IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI
               IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI
             IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI
            IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
           MMMMMMMMMMMMMMMMMMMMMMMMIIII    IIIIIMMMMMMMMMMMMMMMMMMMMMMMI
          MMMMMMMMMMMMMMMMMMMMMII                IIMMMMMMMMMMMMMMMMMMMMMI
         MMMMMMMMMMMMMMMMMMMII                       IMMMMMMMMMMMMMMMMMMM
        IMMMMMMMMMMMMMMMMMMI                           IMMMMMMMMMMMMMMMMMM
       IMMMMMMMMMMMMMMMMMI         IIIIIIIIIIII         IMMMMMMMMMMMMMMMMMI
       MMMMMMMMMMMMMMMMMI        IIIIIIIIIIIIIIIII       IMMMMMMMMMMMMMMMMM
      IMMMMMMMMMMMMMMMMI       IIIIIIIIIIIIIIIIIIII       IMMMMMMMMMMMMMMMMI
      IMMMMMMMMMMMMMMMM       IIIIIIIIIIIIIIIIIIIIII       IMMMMMMMMMMMMMMMM
      MMMMMMMMMMMMMMMMI       IIIIIIIIIIIIIIIIIIIIIII      IMMMMMMMMMMMMMMMM
      MMMMMMMMMMMMMMMMI       IIIIIIIIIIIIIIIIIIIIIII      IMMMMMMMMMMMMMMMM
      MMMMMMMMMMMMMMMMI       IIIIIIIIIIIIIIIIIIIIIII      IMMMMMMMMMMMMMMMM
      IMMMMMMMMMMMMMMMM       IIIIIIIIIIIIIIIIIIIIII       IMMMMMMMMMMMMMMMM
      IMMMMMMMMMMMMMMMMI       IIIIIIIIIIIIIIIIIIII       IMMMMMMMMMMMMMMMMI
       MMMMMMMMMMMMMMMMMI        IIIIIIIIIIIIIIII        IMMMMMMMMMMMMMMMMM
       IMMMMMMMMMMMMMMMMMI          IIIIIIIIIII         IMMMMMMMMMMMMMMMMMI
        IMMMMMMMMMMMMMMMMMM          IIIIIIII          IMMMMMMMMMMMMMMMMMM
         MMMMMMMMMMMMMMMMMMMII       IIIIIIII       IIMMMMMMMMMMMMMMMMMMM
          MMMMMMMMMMMMMMMMMMMMMI    IIIIIIIIII     MMMMMMMMMMMMMMMMMMMMMI
           IMMMMMMMMMMMMMMMMMMI     IIIIIIIIII     IMMMMMMMMMMMMMMMMMMM
            IMMMMMMMMMMMMMMMMI      IIIIIIIIII      IMMMMMMMMMMMMMMMMM
             IMMMMMMMMMMMMMMI      IIIIIIIIIIII      IMMMMMMMMMMMMMMI
               IMMMMMMMMMMMI       IIIIIIIIIIII        MMMMMMMMMMMI
                 IMMMMMMMM         IIIIIIIIIIII         IMMMMMMMI
                   IIMMMM         IIIIIIIIIIIIII         IMMMII
                      II          IIIIIIIIIIIIII          II
                                  IIIIIIIIIIIIII
                                  IIIIIIIIIIIIII

      ~~~~~~~~~~~~ Anarcho-Tech NYC - Virtual Private Networking ~~~~~~~~~~~

      Your lab environment with OpenVPN installed is now ready. There are
      client and server OpenVPN configurations available for you to explore
      at `/etc/openvpn/{client,server}` on all the machines in the lab.

      Log in to the machine that will become your VPN server with:

          vagrant ssh server

      Then explore the OpenVPN configurations, as well as the systemd units
      installed by the OpenVPN packages, to connect the server with one or
      more client machines (`vagrant ssh client`) over the VPN tunnel.

      Good luck!

      Please use what you learn here for the betterment of humanity. Only share what
      you know with the people who you believe will do the same. Remember, intention
      is not impact. Kill all Nazis, kill all cops, especially the ones inside ourselves.
    EOF
  end
end
