Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Provision with Minikube for learning, by default.
  config.vm.provision "minikube", type: "shell", path: "provision/minikube.sh"

  # Optionally, allow manual provisioning with `kubeadm` as well.
  config.vm.provision "manual-cluster", run: "never", type: "shell", path: "provision/manual-cluster.sh", args: [
    "10.244.0.0/16", # Kubernetes pod network CIDR IP address range.

    # CNI plugin YAML manifest URL.
    "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
  ]

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus   = 2
  end
  config.vm.post_up_message = <<~EOF
                                      .                   .
                                  _..-''"""\\          _.--'"""\\
                                  |         L         |        \\
                      _           / _.-.---.\\.        / .-.----.\\
                    _/-|---     _/<"---'"""""\\\\`.    /-'--''"""""\\
                   |       \\     |            L`.`-. |            L
                   /_.-.---.L    |            \\  \\  `|            J`.
                 _/--'""""  \\    F            \\L  \\  |             L
                   L      `. L  J  _.---.-"""-.\\`. L_/ _.--|"""""--.\\ `.
                   |        \\+. /-"__.--'""""   \\ `./'"---'""""""   \\`. `.
                   F   _____ \\ `F"        `.     \\  \\                L `.
                  /.-'"_|---'"\\ |           `    JL |                 L  `.`.
                 <-'""         \\|    _.-.------._ A J    _.-.-----`.--|   ``.`.
                  L         `. |/.-'"_.-`---'""\\."| /-'"---'"""""   \\`.\\.  \\ `.`.
                  |  _.------\\.<'"""            L\\ L\\                `.`\\`. \\  `.
             _.-'//'"--'"""   L\\|       ________\\ `.F     ___.-------._L \\ `-\\   \\`.
            /___| F             F _.--'"_|-------L  /_.-'"_.-|-'"""""""\\  L   L   `.`.
                | F  _.-'|"""""/'"-'"""          J <'"""                L J   |     `.`.
                |/-'-''/|""\\ )-|\\                 F \\                   |  L .'"""`\\""-\\\\_
                 F`-'-'-(`-')  | \\                F  \\                  |___`"""`.""`.-'"
    ------------/        `-'---|  F               L   L             __     |"""""`-'"__________
              .'_         |    |__L          __  J__  |    _.--'""""   `".----'".'
             '""""""""""""|--._+--F _.-'""||"   """___/.-'"   ||-'"/""""" \\_. .'
             J------------(___\\__/'_____.--------'-------'""""""""           /
             `-.                                        _.__.__.__.____     J_.-._
        .'`-._ (-`--`---.'--._`---._.-'`-._.-'_.-'``-._'               `-''-'

    ~~~~~~~~~~~~~~~~~~~~~~ Anarcho-Tech NYC - Introduction to Kubernetes ~~~~~~~~~~~~~~~~~~~~~~
  EOF

  if ARGV.include?('--provision-with') && ARGV.include?('manual-cluster')
    config.vm.post_up_message << <<~EOF
      Your single-node Kubernetes cluster was manually provisioned. A
      recent version of `kubeadm`, `kubectl`, and the `kubelet` are
      now ready for your use.

      Log in to your lab environment

          vagrant ssh
          kubectl -n kube-system get pods
    EOF
  else
    config.vm.post_up_message << <<~EOF
      Your Kubernetes learning environment is ready. It is provisioned
      with a recent version of Minikube.

      Log in to your lab environment and then begin to explore Minikube
      and the Kubernetes framework:

          vagrant ssh -- -X               # Log in with X11 forwarding.
          minikube status                 # Ensure Minikube is running.
          kubectl -n kube-system get pods # See Kubernetes system resources.
          minikube dashboard &            # Start the Web-based Dashboard.
    EOF
  end
end
