Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  # TODO: Provision a bunch of example user accounts.
  #
  #       Fill those user accounts with some interesting data.
  #       For example, run a server with a directory traversal
  #       vulnerability as a given user. Make sure that user
  #       has some "private" files that can be read.
  #
  #       Make another user account whose `umask` is set insecurely
  #       and give that user a fictious password set in one of
  #       their home folder's dotfiles, etc.

  config.vm.provision "Create accounts", type: "shell", inline: <<-SHELL
    # Set up the base system.
    apt update
    apt upgrade --yes
    apt install finger

    # Add some example user accounts.
    users=(labadmin alice bob mallory)
    adduser --disabled-password --gecos 'Lab Administrator,401,555-523-2366,555-000-0001,Educational Services Dept.' ${users[0]}
    adduser --disabled-password --gecos 'Alice,101,555-002-5423,555-000-0002,Student Center' ${users[1]}
    adduser --disabled-password --gecos 'Bob,201,555-020-1262,555-000-0003,Student Center' ${users[2]}
    adduser --disabled-password --gecos 'Malicious Mallory,301,555-625-5679,555-000-0004,Student Center' ${users[3]}

    # Configure SSH keys for the example user accounts.
    rsync -rv /vagrant/provision/home/ /home/
    for user in ${users[*]}; do
        cp "/home/$user/.ssh/id_rsa.pub" "/home/$user/.ssh/authorized_keys"
        chown -R "$user:$user" "/home/$user/.ssh"
        chmod 700 "/home/$user/.ssh"
        chmod 600 "/home/$user/.ssh/"*
    done
  SHELL
end
