Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "secacct-practice-lab"

  config.vm.provider "virtualbox" do |v|
    # Set a name to avoid VirtualBox bug.
    # See: https://github.com/hashicorp/vagrant/issues/9524
    v.name = "securing-shell-account-anarchotech-practice-lab"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Set up the base system.
    apt update
    apt upgrade --yes
    apt install finger links

    # Add some example user accounts.
    users=(labadmin alice bob mallory rapinbill)
    adduser --disabled-password --add_extra_groups --gecos 'Lab Administrator,401,555-523-2366,555-000-0001,Educational Services Dept.' ${users[0]}
    adduser --disabled-password --add_extra_groups --gecos 'Adventurous Alice,101,555-002-5423,555-000-0002,Student Center' ${users[1]}
    adduser --disabled-password --add_extra_groups --gecos 'Boring Bob,201,555-020-1262,555-000-0003,Student Center' ${users[2]}
    adduser --disabled-password --add_extra_groups --gecos 'Malicious Mallory,301,555-625-5679,555-000-0004,Student Center' ${users[3]}
    adduser --disabled-password --add_extra_groups --gecos 'Ricky Vaughn,202,555-555-5555,555-555-5555,Economics' ${users[4]}

    # Set up users's home directories...and all that that implies.
    rsync --verbose --recursive --links /vagrant/provision/home/ /home/
    for user in ${users[*]}; do
        # These SSH keys were generated ahead of time and placed into
        # the host specifically so that they can be used to login via
        # a proper `login(1)` session over SSH with Vagrant. The keys
        # were generated in a loop using an invocation of the form:
        #
        # ```sh
        # ssh-keygen -t rsa -b 2048 -N '' \
        #     -C "$user@securing-shell-accounts.lab.anarchotech.invalid" \
        #     -f "provision/home/$user/.ssh/id_rsa"
        # ```
        #
        # Once generated and provisioned, you can log in to one of the
        # given user accounts with `vagrant`'s SSH feature as follows:
        #
        # ```sh
        # vagrant ssh -- -l $user -i provision/home/$user/.ssh/id_rsa
        # ```
        cp "/home/$user/.ssh/id_rsa.pub" "/home/$user/.ssh/authorized_keys"
        chown -R "$user:$user" "/home/$user/"
        chmod 700 "/home/$user/.ssh"
        chmod 600 "/home/$user/.ssh/"*
    done

    # Install the login greeting, the "message of the day."
    cp /vagrant/provision/etc/motd /etc/motd

    # Give users who will be running (vulnerable!) daemons for demo
    # purposes permission to have their user systemd instance linger.
    loginctl enable-linger labadmin
  SHELL
end
