Vagrant.configure("2") do |config|

  config.vm.define "client" do |c|
    c.vm.box = "ubuntu/bionic64"
    c.vm.provision "shell", path: "provision/client.sh"
    c.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
    end
  end

  # TODO: Set up the Proxmox cluster itself, as well.

end
