Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
  end

  lab_vms = ["client", "server"]
  lab_vms.each do |m|
    config.vm.define m do |c|
    end
  end

end
