Vagrant.configure("2") do |config|

  config.vm.define "client" do |c|
    c.vm.box = "ubuntu/bionic64"
    c.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "server" do |c|
    c.vm.box = "ubuntu/bionic64"
    c.vm.network "private_network", type: "dhcp"
  end

end
