Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # Forward Prometheus Web UI port.
  config.vm.network "forwarded_port", guest: 9090, host: 9090,
    auto_correct: true

  # Forward Alertmanager UI port.
  config.vm.network "forwarded_port", guest: 9093, host: 9093,
    auto_correct: true

  # Forward MailHog Web UI port.
  config.vm.network "forwarded_port", guest: 8025, host: 8025,
    auto_correct: true

  # Forward Grafana server Web UI port.
  config.vm.network "forwarded_port", guest: 3000, host: 3000,
    auto_correct: true

  config.vm.provision "shell", path: "provision/provision.sh"

  config.vm.post_up_message = <<~EOF
     .    '                   .  "   '
                .  .  .                 '      '
        "`       .   .
                                         '     '
      .    '      _______________
              ==c(___(o(______(_()
                      \\=\\
                       )=\\
                      //|\\\\
                     //|| \\\\
                    // ||  \\\\
                   //  ||   \\\\
                  //         \\\\

    ~~~~~~~~~~~~~~ Anarcho-Tech NYC ~~~~~~~~~~~~~~
    ~~~~~ Introduction to Service Monitoring ~~~~~

    Your lab environment has a single Prometheus server installation
    along with an Alertmanager. Grafana is also available.

    Explore the Web interfaces at the following addresses:

        http://localhost:9090/ # Prometheus
        http://localhost:9093/ # Alertmanager
        http://localhost:3000/ # Grafana.

    Once you're familiar with the Web interface, log in to the lab to
    explore the configuration of these components:

        vagrant ssh        # Log in.
        cd /etc/prometheus # Explore component configs.

    For viewing email alerts, Mailhog is available at:

        http://localhost:8025/

    Please use what you learn here for the betterment of humanity. Only share what
    you know with the people who you believe will do the same. Remember, intention
    is not impact. Kill all Nazis, kill all cops, especially the ones inside ourselves.
  EOF
end
